# Generated by Django 5.1.6 on 2025-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('legal_address', models.CharField(max_length=250, verbose_name='Юридический адрес')),
                ('physical_address', models.CharField(max_length=250, verbose_name='Физический адрес')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'legal_address', 'physical_address'), name='unique_clinic_address')],
            },
        ),
    ]
