# Generated by Django 5.1.6 on 2025-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания консультации')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Время начала приема')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания приема')),
                ('status', models.CharField(choices=[('Confirmed', 'Подтверждена'), ('Waiting', 'Ожидает'), ('Started', 'Начата'), ('Finished', 'Завершена'), ('Paid', 'Оплачена')], default='Waiting', max_length=15, verbose_name='Статус консультации')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ('-created_at',),
            },
        ),
    ]
