# Generated by Django 5.1.6 on 2025-03-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to='users.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to='users.patient', verbose_name='Пациент'),
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_time'), name='unique_doctor_consultation_time'),
        ),
    ]
